services:
  ai-maria:
    container_name: ai-maria
    image: mariadb:12.1.2
    restart: always
    command: 
      - --local-infile=1
    ports:
      - 23306:3306
    networks:
      - ai-agent
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
      - data-mariadb:/var/lib/mysql:rw
    environment:
      - MARIADB_HOST=localhost
      - MARIADB_PORT=23306
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=db_board
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8

  ai-back:
    container_name: ai-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: uv:1
    ports:
      - 8001:8000
    networks:
      - ai-agent
    depends_on:
      - ai-maria
    working_dir: /workspace
    

  ai-front:
    container_name: ai-front
    build:
      context: ./frontend
      dockerfile: Dockerfile   
    ports:
      - 80:80
    networks:
      - ai-agent
    working_dir: /workspace


networks:
  ai-agent:
    driver: bridge

volumes:
  data-mariadb:
    external: true # 기존 Volume 사용 옵션!!
  uploads: