FROM python:3.13.11

RUN apt-get update
RUN apt-get upgrade -y
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pip install uv

WORKDIR /workspace

# 의존성 파일 먼저 복사 (캐시 활용)
COPY pyproject.toml uv.lock ./

# 의존성 설치
RUN uv sync

# 전체 코드 복사
COPY . .

EXPOSE 8000

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]