name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - name: Check PowerShell
      #   run: $PSVersionTable
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # - name: Check Node.js version
      #   run: node -v
      - name: npm install
        working-directory: ./frontend
        run: npm i

      - name: npm build
        working-directory: ./frontend
        run: npm run build

      # 2가지 방법이 존재
      # - name: nginx
      #   working-directory: ./frontend
      #   run: docker run -d -p 80:80 -v ./dist:/usr/share/nginx/html --name web nginx:1.28

      # docker rm -f web 명령어는 기존 컨테이너 제거이기 때문에 최초 실행 시에는 오류가 발생할 수 있음 
      # 그렇다 보니 최초에는 추가하면 안됨

      - name: nginx
        run: |
          docker rm -f web
          docker run -d -p 80:80 -v ./frontend/dist:/usr/share/nginx/html -v ./frontend/default.conf:/etc/nginx/conf.d/default.conf --name web nginx:1.28

      - name: uv image build
        working-directory: ./backend
        run: docker build -t uv:1 .

      - name: fastapi run
        working-directory: ./backend
        run: docker run -d -p 8001:8000 -v .:/workspace --name back uv:1